services:
  - type: web
    name: evidara
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CLOUDINARY_URL
        sync: false